[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
  "requests",
  "requests_oauthlib",
  'importlib-metadata; python_version<"3.8"',
]
name = "message_senders"
version = "0.0.1"
